name: Run GitHub Gist API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.PAT_Gist }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config file
        run: |
          mkdir -p config
          echo "[github]" > config/config.ini
          echo "base_url = https://api.github.com" >> config/config.ini
          echo "access_token = ${GITHUB_ACCESS_TOKEN}" >> config/config.ini

      - name: Print Current Working Directory
        run: pwd

      - name: List Directory
        run: ls

      - name: Run tests
        run: |
          pytest tests/test_gist_api.py
